stages:
  - test
  - build
  - deploy


.build_template: &build_definition
  image: node:8.12.0
  stage: build
  script:
    - yarn install
    - yarn build
    - ls -la
  artifacts:
    paths:
      - dist

build_stg:
  <<: *build_definition
  variables:
    VUE_APP_SERVER_API_ENDPOINT: $STG_VUE_APP_SERVER_API_ENDPOINT
    VUE_APP_REQUEST_TIMEOUT: $STG_VUE_APP_REQUEST_TIMEOUT
  only:
    - production



.deploy_template: &deploy_definition
  image: python:3.6
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - pip install awscli
    - aws s3 sync ./dist/ s3://$VUE_APP_S3_BUCKET_NAME/$VUE_APP_S3_SEGMENT_PATH/
      --exclude "*"
      --include "*.html" --include "*.css" --include "*.png" --include "*.jpg" --include "*.js" --include "*.map"
      --delete
      --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      --exact-timestamps

deploy_stg:
  <<: *deploy_definition
  variables:
    VUE_APP_S3_BUCKET_NAME: $STG_VUE_APP_S3_BUCKET_NAME
  only:
    - production
