version: "3.6"

services:
  front:
    build: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command: 'bash -c "yarn install && yarn run serve"'
    volumes:
      - .:/var/segment
